version: '3.0'

services:
  wordpress:
    image: wordpress:6.5.2-fpm-alpine
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME:-testdb}
      - WORDPRESS_DB_HOST=${DB_HOST:-mysql}
      - WORDPRESS_DB_PORT=${DB_PORT:-3306}
      - WORDPRESS_DB_USER=${DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=
      - WORDPRESS_TABLE_PREFIX=wp_
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    networks:
      - wp-network

  nginx:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME}-nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - '8888:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - wordpress:/var/www/html
    networks:
      - wp-network

  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      # MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME:-testdb}
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - wp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_NAME}-phpmyadmin
    restart: unless-stopped
    env_file: .env
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - wp-network

volumes:
  dbdata:
  wordpress:

networks:
  wp-network:
    driver: bridge
