version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - wordpress:/var/www/html
      - ./certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress
    networks:
      - wp-network
    restart: always

  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}-mysql
    environment:
      # MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME:-myapp}
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - wp-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    image: wordpress:fpm-alpine
    container_name: ${APP_NAME}
    volumes:
    - wordpress:/var/www/html
    - ./wp-content:/var/www/html/wp-content:rw
    - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME:-myapp}
      - WORDPRESS_DB_HOST=${DB_HOST:-mysql}
      - WORDPRESS_DB_PORT=${DB_PORT:-3306}
      - WORDPRESS_DB_USER=${DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=
      - WORDPRESS_TABLE_PREFIX=${DB_TABLE_PREFIX:-wp_}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - wp-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - wp-network
    restart: always

volumes:
  dbdata:
  wordpress:

networks:
  wp-network:
    driver: bridge